package org.personal.simulator.service;

import org.personal.simulator.enums.SimulatorStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

/**
 * Service for sending async callbacks to the payment backend.
 * Simulates the real PSP behavior where callbacks are sent after processing.
 */
@Service
public class CallbackService {

    private static final Logger log = LoggerFactory.getLogger(CallbackService.class);

    private final RestTemplate restTemplate;

    @Value("${simulator.callback.default-delay-ms:2000}")
    private long defaultDelayMs;

    @Value("${simulator.callback.retry-count:3}")
    private int retryCount;

    @Value("${simulator.callback.retry-delay-ms:1000}")
    private long retryDelayMs;

    public CallbackService(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    /**
     * Schedule an async callback to the backend.
     *
     * @param transactionId   Backend transaction ID
     * @param pspReferenceId  PSP reference ID generated by simulator
     * @param bankReferenceId Bank reference ID
     * @param status          Final status (SUCCESS/FAILED)
     * @param failureReason   Reason if failed
     * @param callbackUrl     URL to call back (backend's callback endpoint)
     * @param delayMs         Delay before sending callback
     */
    @Async("simulatorTaskExecutor")
    public CompletableFuture<Void> scheduleCallback(
            String transactionId,
            String pspReferenceId,
            String bankReferenceId,
            SimulatorStatus status,
            String failureReason,
            String callbackUrl,
            long delayMs) {

        return CompletableFuture.runAsync(() -> {
            try {
                // Simulate processing delay
                long actualDelay = delayMs > 0 ? delayMs : defaultDelayMs;
                log.info("Scheduling callback for txn={} in {}ms", transactionId, actualDelay);
                TimeUnit.MILLISECONDS.sleep(actualDelay);

                // Build callback payload (matches UpiCallbackRequest in backend)
                Map<String, Object> payload = new HashMap<>();
                payload.put("transactionId", transactionId);
                payload.put("pspReferenceId", pspReferenceId);
                payload.put("bankReferenceId", bankReferenceId);
                payload.put("status", mapStatusToBackend(status));
                if (failureReason != null) {
                    payload.put("failureReason", failureReason);
                }

                // Send callback with retry logic
                sendCallbackWithRetry(callbackUrl, payload);

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                log.warn("Callback interrupted for txn={}", transactionId);
            }
        });
    }

    private void sendCallbackWithRetry(String callbackUrl, Map<String, Object> payload) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        // Add signature header for verification (simplified)
        headers.set("X-Simulator-Signature", generateSignature(payload));

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(payload, headers);

        for (int attempt = 1; attempt <= retryCount; attempt++) {
            try {
                log.info("Sending callback attempt {}/{} to {}: txnId={}",
                        attempt, retryCount, callbackUrl, payload.get("transactionId"));
                restTemplate.postForEntity(callbackUrl, request, String.class);
                log.info("Callback successful: txnId={}, status={}",
                        payload.get("transactionId"), payload.get("status"));
                return;
            } catch (Exception e) {
                log.warn("Callback attempt {} failed: {}", attempt, e.getMessage());
                if (attempt < retryCount) {
                    try {
                        long backoffDelay = retryDelayMs * attempt; // Linear backoff
                        log.info("Retrying in {}ms...", backoffDelay);
                        TimeUnit.MILLISECONDS.sleep(backoffDelay);
                    } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt();
                        return;
                    }
                }
            }
        }

        log.error("All callback attempts failed for txnId={}", payload.get("transactionId"));
    }

    /**
     * Map simulator status to backend TransactionStatus string.
     */
    private String mapStatusToBackend(SimulatorStatus status) {
        return switch (status) {
            case SUCCESS -> "SUCCESS";
            case FAILED -> "FAILED";
            case PENDING -> "PENDING";
        };
    }

    /**
     * Generate a simple signature for callback verification.
     * In production, use HMAC-SHA256 with shared secret.
     */
    private String generateSignature(Map<String, Object> payload) {
        // Simplified - in production use proper HMAC
        String data = payload.get("transactionId") + "|" + payload.get("status");
        return "SIM_" + data.hashCode();
    }
}
